version: '3.6'
services:
  app:
    image: acodevs/ionic-framework:2022.12.10-vue
    command: 'ionic serve --external'
    container_name: ionic-framework-test-app
    ports:
      - '8100:8100'
      - '35729:35729'
    expose:
      - 8100
      - 35729
    working_dir: /tmp/myNewProject
    volumes:
      - "./app/:/tmp/myNewProject"
      - "./cordova/:/tmp/myApp"
